POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "contact@web-crafter.site",
  "password": "jack",
  "username": "jack"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@web-crafter.site",
  "password": "admin"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "contact@web-crafter.site",
  "password": "jack"
}

###
GET http://localhost:3000/users

###
POST http://localhost:3000/mail
Content-Type: application/json

{
  "email": "mohamet.almeari@gmail.com",
  "subject": "Test Email",
  "message": "<p style='color: blue;'>Hello World! This is a <b>test email</b> from Jack.</p>",
  "senderUsername": "contact",
  "senderName": "Jack"
}